const STORAGE_KEY='nextMoveData_v2';
const LEGACY_KEY='projectPulseData_v1';
const DEFAULT_DATA={projects:[],tasks:[]};
const CLOUD_CONFIG_KEY='nextMoveCloudConfig_v1';
const CLOUD_SESSION_KEY='nextMoveCloudSession_v1';
const LOCAL_UPDATED_KEY='nextMoveLocalUpdatedAt_v1';
let data=loadData();
let cloudBusy=false, cloudTimer=null;
const $=id=>document.getElementById(id);
const IS_NATIVE=location.protocol==='file:' && /Android/i.test(navigator.userAgent);
function uid(){return (crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));}
function loadData(){try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_KEY)||'{}';const loaded={...DEFAULT_DATA,...JSON.parse(raw)};if(!localStorage.getItem(LOCAL_UPDATED_KEY)&&(loaded.projects?.length||loaded.tasks?.length)){const stamps=[...(loaded.projects||[]),...(loaded.tasks||[])].map(x=>x.updatedAt||x.createdAt).filter(Boolean).sort();localStorage.setItem(LOCAL_UPDATED_KEY,stamps.at(-1)||new Date().toISOString());}return loaded}catch{return structuredClone(DEFAULT_DATA)}}
function saveData(skipCloud=false){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));localStorage.setItem(LOCAL_UPDATED_KEY,new Date().toISOString());renderAll();if(!skipCloud)queueCloudPush();}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function localInputValue(iso){if(!iso)return'';const d=new Date(iso),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`;}
function parseLocalDateTime(v){return v?new Date(v).toISOString():'';}
function startOfDay(d=new Date()){return new Date(d.getFullYear(),d.getMonth(),d.getDate());}
function endOfDay(d=new Date()){return new Date(d.getFullYear(),d.getMonth(),d.getDate(),23,59,59,999);}
function dueState(t){if(t.completed||!t.dueAt)return'';const due=new Date(t.dueAt),now=new Date();if(due<now)return'overdue';if(due>=startOfDay(now)&&due<=endOfDay(now))return'today';return'upcoming';}
function priorityRank(p){return {high:0,medium:1,low:2}[p]??3;}
function taskSort(a,b){if(a.completed!==b.completed)return a.completed?1:-1;const sa=dueState(a),sb=dueState(b),rank={overdue:0,today:1,upcoming:2,'':3};if(rank[sa]!==rank[sb])return rank[sa]-rank[sb];if(a.dueAt&&b.dueAt&&a.dueAt!==b.dueAt)return new Date(a.dueAt)-new Date(b.dueAt);return priorityRank(a.priority)-priorityRank(b.priority);}
function formatDate(iso){if(!iso)return'No due date';return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:new Date(iso).getFullYear()!==new Date().getFullYear()?'numeric':undefined,hour:'numeric',minute:'2-digit'}).format(new Date(iso));}
function relativeDue(iso){if(!iso)return'';const ms=new Date(iso)-new Date(),mins=Math.round(Math.abs(ms)/60000);let txt;if(mins<60)txt=`${Math.max(1,mins)} min`;else if(mins<1440)txt=`${Math.round(mins/60)} hr`;else txt=`${Math.round(mins/1440)} day${Math.round(mins/1440)===1?'':'s'}`;return ms<0?`${txt} overdue`:`due in ${txt}`;}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);}
function projectName(id){return data.projects.find(p=>p.id===id)?.name||'No project';}
function nativeCommand(action,params={}){if(!IS_NATIVE||!window.Android)return false;try{if(action==='schedule')Android.schedule(String(params.id??''),String(params.title??''),String(params.body??''),String(params.first??0),String(params.interval??0));else if(action==='cancel')Android.cancel(String(params.id??''));else if(action==='test')Android.test();else if(action==='requestNotifications')Android.requestNotifications();else if(action==='configureBackgroundSync')Android.configureBackgroundSync(String(params.url||''),String(params.key||''),String(params.session||'{}'));else if(action==='disableBackgroundSync')Android.disableBackgroundSync();return true;}catch(e){console.warn('Native bridge error',e);return false;}}
function syncNativeReminder(t){if(!IS_NATIVE)return;if(t.completed||!t.dueAt||Number(t.reminderBefore)<0){nativeCommand('cancel',{id:t.id});return;}const due=new Date(t.dueAt).getTime(),first=due-Number(t.reminderBefore)*60000,interval=Math.max(0,Number(t.repeatMins)||0)*60000;let body=projectName(t.projectId);if(t.assignee)body+=(body?' • ':'')+`Assigned: ${t.assignee}`;nativeCommand('schedule',{id:t.id,title:t.title,body,first,interval});}
function syncAllNativeReminders(){if(!IS_NATIVE)return;data.tasks.forEach((t,i)=>setTimeout(()=>syncNativeReminder(t),i*70));}

function getCloudConfig(){try{return JSON.parse(localStorage.getItem(CLOUD_CONFIG_KEY)||'{}')}catch{return{}}}
function setCloudConfig(c){localStorage.setItem(CLOUD_CONFIG_KEY,JSON.stringify(c));}
function getCloudSession(){try{return JSON.parse(localStorage.getItem(CLOUD_SESSION_KEY)||'{}')}catch{return{}}}
function setCloudSession(s){if(s&&s.access_token){localStorage.setItem(CLOUD_SESSION_KEY,JSON.stringify(s));const c=getCloudConfig();nativeCommand('configureBackgroundSync',{url:c.url,key:c.key,session:JSON.stringify(s)});}else{localStorage.removeItem(CLOUD_SESSION_KEY);nativeCommand('disableBackgroundSync');}}
function cloudBase(){return (getCloudConfig().url||'').replace(/\/$/,'');}
function cloudHeaders(token,extra={}){const c=getCloudConfig();return {'apikey':c.key||'','Authorization':`Bearer ${token||''}`,'Content-Type':'application/json',...extra};}
function jwtSub(token){try{const b=token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(decodeURIComponent(atob(b).split('').map(c=>'%'+('00'+c.charCodeAt(0).toString(16)).slice(-2)).join(''))).sub||''}catch{return''}}
function setSyncStatus(text,cls='offline'){const el=$('syncStatus');if(!el)return;el.textContent=text;el.className='sync-status '+cls;}
function setSyncMeta(text){const el=$('syncMeta');if(el)el.textContent=text;}
function validCloudConfig(){const c=getCloudConfig();return /^https:\/\//.test(c.url||'')&&!!c.key;}
function loadCloudFields(){const c=getCloudConfig();if($('cloudUrl'))$('cloudUrl').value=c.url||'';if($('cloudKey'))$('cloudKey').value=c.key||'';if($('cloudEmail'))$('cloudEmail').value=c.email||'';const s=getCloudSession();if(s.access_token)setSyncStatus(navigator.onLine?'Connected':'Offline','ok');}
function saveCloudFields(){const c={url:$('cloudUrl').value.trim().replace(/\/$/,''),key:$('cloudKey').value.trim(),email:$('cloudEmail').value.trim()};setCloudConfig(c);const ss=getCloudSession();if(ss.access_token)nativeCommand('configureBackgroundSync',{url:c.url,key:c.key,session:JSON.stringify(ss)});setSyncStatus('Connection saved','ok');setSyncMeta('Connection settings saved on this device. Sign in to start syncing.');return c;}
async function cloudRequest(path,opts={}){const c=getCloudConfig();if(!validCloudConfig())throw new Error('Enter and save your Supabase Project URL and publishable/anon key first.');const res=await fetch(c.url+path,{...opts,headers:{'apikey':c.key,'Content-Type':'application/json',...(opts.headers||{})}});let body=null;const txt=await res.text();if(txt){try{body=JSON.parse(txt)}catch{body=txt}}if(!res.ok)throw new Error(body?.msg||body?.message||body?.error_description||body?.error||`Cloud request failed (${res.status})`);return body;}
async function ensureSession(){let s=getCloudSession();if(!s.access_token)throw new Error('Sign in first.');const exp=s.expires_at?Number(s.expires_at)*1000:0;if(exp&&Date.now()<exp-60000)return s;if(!s.refresh_token)return s;const r=await cloudRequest('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token})});setCloudSession(r);return r;}
async function cloudSignIn(){saveCloudFields();const email=$('cloudEmail').value.trim(),password=$('cloudPassword').value;if(!email||!password)throw new Error('Enter your email and password.');setSyncStatus('Signing in…','syncing');const r=await cloudRequest('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});setCloudSession(r);$('cloudPassword').value='';setSyncStatus('Connected','ok');await syncCloud('login');toast('Signed in and synced');}
async function cloudSignUp(){saveCloudFields();const email=$('cloudEmail').value.trim(),password=$('cloudPassword').value;if(!email||!password)throw new Error('Enter an email and password first.');setSyncStatus('Creating account…','syncing');const r=await cloudRequest('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})});if(r?.access_token){setCloudSession(r);$('cloudPassword').value='';setSyncStatus('Connected','ok');await syncCloud('signup');toast('Account created and synced');}else{setSyncStatus('Check your email','ok');setSyncMeta('Supabase requires email confirmation. Confirm the message, then return here and sign in.');toast('Account created. Check your email to confirm it.');}}
async function cloudSignOut(){try{const s=getCloudSession();if(s.access_token)await cloudRequest('/auth/v1/logout',{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`}});}catch(e){console.warn(e)}setCloudSession(null);setSyncStatus('Signed out','offline');setSyncMeta('Local data remains on this device.');toast('Signed out');}
async function fetchRemote(session){const r=await fetch(cloudBase()+'/rest/v1/nextmove_sync?select=payload,client_updated_at&limit=1',{headers:cloudHeaders(session.access_token)});if(!r.ok)throw new Error((await r.text())||`Sync fetch failed (${r.status})`);const rows=await r.json();return rows[0]||null;}
async function pushRemote(session){const userId=jwtSub(session.access_token);if(!userId)throw new Error('Could not read user ID from the login session.');const stamp=localStorage.getItem(LOCAL_UPDATED_KEY)||new Date().toISOString();const body={user_id:userId,payload:data,client_updated_at:stamp};const r=await fetch(cloudBase()+'/rest/v1/nextmove_sync?on_conflict=user_id',{method:'POST',headers:cloudHeaders(session.access_token,{'Prefer':'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.text())||`Sync upload failed (${r.status})`);return stamp;}
async function syncCloud(reason='manual'){if(cloudBusy||!navigator.onLine||!validCloudConfig()||!getCloudSession().access_token)return false;cloudBusy=true;setSyncStatus('Syncing…','syncing');try{const session=await ensureSession();const remote=await fetchRemote(session);const localStamp=localStorage.getItem(LOCAL_UPDATED_KEY)||'1970-01-01T00:00:00.000Z';if(!remote){await pushRemote(session);setSyncMeta('Uploaded this device as the first cloud copy.');}else{const remoteStamp=remote.client_updated_at||'1970-01-01T00:00:00.000Z',incoming=remote.payload||DEFAULT_DATA;const localCount=(data.projects?.length||0)+(data.tasks?.length||0),remoteCount=(incoming.projects?.length||0)+(incoming.tasks?.length||0);if(localCount>0&&remoteCount===0){await pushRemote(session);setSyncMeta('Uploaded existing device data to the empty cloud copy.');}else if(remoteCount>0&&localCount===0){data={projects:incoming.projects||[],tasks:incoming.tasks||[]};localStorage.setItem(STORAGE_KEY,JSON.stringify(data));localStorage.setItem(LOCAL_UPDATED_KEY,remoteStamp);renderAll();syncAllNativeReminders();setSyncMeta(`Downloaded cloud data • ${new Date(remoteStamp).toLocaleString()}`);}else if(new Date(remoteStamp).getTime()>new Date(localStamp).getTime()+500){if(Array.isArray(incoming.projects)&&Array.isArray(incoming.tasks)){data={projects:incoming.projects,tasks:incoming.tasks};localStorage.setItem(STORAGE_KEY,JSON.stringify(data));localStorage.setItem(LOCAL_UPDATED_KEY,remoteStamp);renderAll();syncAllNativeReminders();setSyncMeta(`Downloaded newer cloud data • ${new Date(remoteStamp).toLocaleString()}`);}}else if(new Date(localStamp).getTime()>new Date(remoteStamp).getTime()+500){await pushRemote(session);setSyncMeta(`Uploaded changes • ${new Date(localStamp).toLocaleString()}`);}else setSyncMeta(`Up to date • ${new Date().toLocaleString()}`);}setSyncStatus('Synced','ok');return true;}catch(e){console.error(e);setSyncStatus('Sync error','error');setSyncMeta(e.message||String(e));if(reason==='manual'||reason==='login')toast(e.message||'Sync failed');return false;}finally{cloudBusy=false;}}
function queueCloudPush(){if(!validCloudConfig()||!getCloudSession().access_token)return;clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>syncCloud('auto'),900);}

function renderAll(){renderCounts();renderAttention();renderNextActions();renderProjects();populateProjectSelects();renderTasks();}
function renderCounts(){const open=data.tasks.filter(t=>!t.completed),now=new Date(),week=new Date(Date.now()+7*86400000);$('overdueCount').textContent=open.filter(t=>t.dueAt&&new Date(t.dueAt)<now).length;$('todayCount').textContent=open.filter(t=>t.dueAt&&new Date(t.dueAt)>=startOfDay(now)&&new Date(t.dueAt)<=endOfDay(now)).length;$('upcomingCount').textContent=open.filter(t=>t.dueAt&&new Date(t.dueAt)>endOfDay(now)&&new Date(t.dueAt)<=week).length;$('openCount').textContent=open.length;}
function taskCard(t){const state=dueState(t),who=t.assignee?`<span class="badge assignee">👤 ${esc(t.assignee)}</span>`:'';return `<article class="item-card ${t.completed?'completed':''}"><div class="item-top"><input class="checkbox task-toggle" type="checkbox" data-id="${t.id}" ${t.completed?'checked':''} aria-label="Complete task"><div class="item-main"><div class="item-title">${esc(t.title)}</div><div class="meta"><span class="badge ${t.priority}">${esc(t.priority)}</span>${who}${state?`<span class="badge ${state}">${state==='overdue'?relativeDue(t.dueAt):state==='today'?'Due today':formatDate(t.dueAt)}</span>`:''}<span>${esc(projectName(t.projectId))}</span>${t.dueAt&&!state?`<span>${formatDate(t.dueAt)}</span>`:''}</div>${t.notes?`<div class="comments">${esc(t.notes)}</div>`:''}</div><div class="item-actions"><button class="icon-btn task-edit" data-id="${t.id}" title="Edit">✎</button><button class="icon-btn task-delete" data-id="${t.id}" title="Delete">×</button></div></div></article>`;}
function renderAttention(){const list=data.tasks.filter(t=>!t.completed&&(dueState(t)==='overdue'||dueState(t)==='today'||(t.dueAt&&new Date(t.dueAt)<=new Date(Date.now()+7*86400000)))).sort(taskSort).slice(0,12);$('attentionList').innerHTML=list.length?list.map(taskCard).join(''):`<div class="empty">Nothing urgent. Suspicious, but enjoy it.</div>`;bindTaskButtons($('attentionList'));}
function renderNextActions(){const ps=data.projects.filter(p=>p.status==='active'&&p.nextAction?.trim()).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority));$('nextActionsList').innerHTML=ps.length?ps.map(p=>`<article class="item-card"><div class="item-title">${esc(p.name)}</div><div class="meta"><span class="badge ${p.priority}">${esc(p.priority)}</span>${p.dueDate?`<span>Target ${new Date(p.dueDate+'T12:00').toLocaleDateString()}</span>`:''}</div><div class="next-action"><strong>Next:</strong> ${esc(p.nextAction)}</div></article>`).join(''):`<div class="empty">No next actions entered yet.</div>`;}
function renderProjects(){const ps=[...data.projects].sort((a,b)=>(a.status==='completed')-(b.status==='completed')||priorityRank(a.priority)-priorityRank(b.priority));$('projectList').innerHTML=ps.length?ps.map(p=>{const tasks=data.tasks.filter(t=>t.projectId===p.id),done=tasks.filter(t=>t.completed).length;return `<article class="item-card ${p.status==='completed'?'completed':''}"><div class="item-top"><div class="item-main"><div class="item-title">${esc(p.name)}</div><div class="meta"><span class="badge ${p.priority}">${esc(p.priority)}</span><span class="badge ${p.status==='completed'?'complete':''}">${esc(p.status.replace('-',' '))}</span>${p.dueDate?`<span>Target ${new Date(p.dueDate+'T12:00').toLocaleDateString()}</span>`:''}</div>${p.nextAction?`<div class="next-action"><strong>Next action:</strong> ${esc(p.nextAction)}</div>`:''}${p.comments?`<div class="comments">${esc(p.comments)}</div>`:''}<div class="project-progress">${done} of ${tasks.length} tasks completed</div></div><div class="item-actions"><button class="icon-btn project-task" data-id="${p.id}" title="Add task">＋</button><button class="icon-btn project-edit" data-id="${p.id}" title="Edit">✎</button><button class="icon-btn project-delete" data-id="${p.id}" title="Delete">×</button></div></div></article>`}).join(''):`<div class="empty">No projects yet. Apparently chaos has not been formally documented.</div>`;document.querySelectorAll('.project-edit').forEach(b=>b.onclick=()=>openProject(b.dataset.id));document.querySelectorAll('.project-task').forEach(b=>b.onclick=()=>openTask('',b.dataset.id));document.querySelectorAll('.project-delete').forEach(b=>b.onclick=()=>deleteProject(b.dataset.id));}
function populateProjectSelects(){const options=data.projects.filter(p=>p.status!=='completed').map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('taskProject').innerHTML='<option value="">No project</option>'+options;const current=$('taskProjectFilter').value;$('taskProjectFilter').innerHTML='<option value="all">All projects</option>'+data.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');if([...$('taskProjectFilter').options].some(o=>o.value===current))$('taskProjectFilter').value=current;}
function renderTasks(){let ts=[...data.tasks];const pf=$('taskProjectFilter').value,sf=$('taskStatusFilter').value,pr=$('taskPriorityFilter').value,af=$('taskAssigneeFilter').value.trim().toLowerCase();if(pf!=='all')ts=ts.filter(t=>t.projectId===pf);if(pr!=='all')ts=ts.filter(t=>t.priority===pr);if(af)ts=ts.filter(t=>(t.assignee||'').toLowerCase().includes(af));if(sf==='open')ts=ts.filter(t=>!t.completed);if(sf==='completed')ts=ts.filter(t=>t.completed);if(sf==='overdue')ts=ts.filter(t=>dueState(t)==='overdue');if(sf==='today')ts=ts.filter(t=>dueState(t)==='today');ts.sort(taskSort);$('taskList').innerHTML=ts.length?ts.map(taskCard).join(''):`<div class="empty">No tasks match that filter.</div>`;bindTaskButtons($('taskList'));}
function bindTaskButtons(root){root.querySelectorAll('.task-toggle').forEach(b=>b.onchange=()=>toggleTask(b.dataset.id,b.checked));root.querySelectorAll('.task-edit').forEach(b=>b.onclick=()=>openTask(b.dataset.id));root.querySelectorAll('.task-delete').forEach(b=>b.onclick=()=>deleteTask(b.dataset.id));}
function toggleTask(id,done){const t=data.tasks.find(x=>x.id===id);if(t){t.completed=done;t.completedAt=done?new Date().toISOString():'';saveData();syncNativeReminder(t);}}
function openProject(id=''){const p=data.projects.find(x=>x.id===id);$('projectDialogTitle').textContent=p?'Edit project':'New project';$('projectId').value=p?.id||'';$('projectName').value=p?.name||'';$('projectPriority').value=p?.priority||'medium';$('projectStatus').value=p?.status||'active';$('projectDueDate').value=p?.dueDate||'';$('projectNextAction').value=p?.nextAction||'';$('projectComments').value=p?.comments||'';$('projectDialog').showModal();}
function openTask(id='',projectId=''){const t=data.tasks.find(x=>x.id===id);$('taskDialogTitle').textContent=t?'Edit task':'New task';$('taskId').value=t?.id||'';$('taskTitle').value=t?.title||'';$('taskProject').value=t?.projectId??projectId??'';$('taskAssignee').value=t?.assignee||'';$('taskPriority').value=t?.priority||'medium';$('taskDueAt').value=localInputValue(t?.dueAt);$('taskReminderBefore').value=String(t?.reminderBefore??1440);$('taskRepeat').value=String(t?.repeatMins??480);$('taskNotes').value=t?.notes||'';$('taskDialog').showModal();}
function deleteProject(id){const p=data.projects.find(x=>x.id===id),count=data.tasks.filter(t=>t.projectId===id).length;if(!confirm(`Delete “${p?.name||'project'}”? ${count?`${count} task(s) will be kept but unassigned.`:''}`))return;data.projects=data.projects.filter(x=>x.id!==id);data.tasks.forEach(t=>{if(t.projectId===id){t.projectId='';syncNativeReminder(t);}});saveData();}
function deleteTask(id){const t=data.tasks.find(x=>x.id===id);if(confirm(`Delete “${t?.title||'this task'}”?`)){nativeCommand('cancel',{id});data.tasks=data.tasks.filter(x=>x.id!==id);saveData();}}
$('projectForm').addEventListener('submit',e=>{e.preventDefault();const id=$('projectId').value,existing=data.projects.find(p=>p.id===id);const p={id:id||uid(),name:$('projectName').value.trim(),priority:$('projectPriority').value,status:$('projectStatus').value,dueDate:$('projectDueDate').value,nextAction:$('projectNextAction').value.trim(),comments:$('projectComments').value.trim(),createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(existing)Object.assign(existing,p);else data.projects.push(p);saveData();$('projectDialog').close();toast('Project saved');});
$('taskForm').addEventListener('submit',e=>{e.preventDefault();const id=$('taskId').value,existing=data.tasks.find(t=>t.id===id),reminderBefore=Number($('taskReminderBefore').value),repeatMins=Number($('taskRepeat').value);const t={id:id||uid(),title:$('taskTitle').value.trim(),projectId:$('taskProject').value,assignee:$('taskAssignee').value.trim(),priority:$('taskPriority').value,dueAt:parseLocalDateTime($('taskDueAt').value),reminderBefore,repeatMins,notes:$('taskNotes').value.trim(),completed:existing?.completed||false,completedAt:existing?.completedAt||'',lastNotifiedAt:existing?.lastNotifiedAt||'',createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(existing)Object.assign(existing,t);else data.tasks.push(t);saveData();$('taskDialog').close();toast('Task saved');syncNativeReminder(t);if(!IS_NATIVE)checkReminders();});
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('addProjectBtn').onclick=()=>openProject();$('addTaskBtn').onclick=()=>openTask();$('quickTaskBtn').onclick=()=>openTask();['taskProjectFilter','taskStatusFilter','taskPriorityFilter'].forEach(id=>$(id).onchange=renderTasks);$('taskAssigneeFilter').oninput=renderTasks;document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(tab.dataset.tab).classList.add('active');});
async function enableNotifications(){if(IS_NATIVE){nativeCommand('requestNotifications');$('notifyBtn').textContent='Reminders requested';toast('Allow NextMove notifications in the Android prompt');return true;}if(!('Notification'in window)){toast('Notifications are not supported in this browser');return false;}const perm=await Notification.requestPermission();if(perm==='granted'){toast('Reminders enabled');$('notifyBtn').textContent='Reminders on';return true;}toast('Notification permission was not granted');return false;}
$('notifyBtn').onclick=enableNotifications;$('testNotifyBtn').onclick=async()=>{if(IS_NATIVE){nativeCommand('test');return;}if(Notification.permission!=='granted'&&!(await enableNotifications()))return;sendNotification('NextMove','Test reminder. The nagging machinery is operational.');};
function sendNotification(title,body){try{new Notification(title,{body,icon:'icons/icon-192.png'});}catch(e){console.warn(e)}}
function checkReminders(){if(IS_NATIVE||!('Notification'in window)||Notification.permission!=='granted')return;const now=Date.now();let changed=false;data.tasks.filter(t=>!t.completed&&t.dueAt&&Number(t.reminderBefore)>=0).forEach(t=>{const due=new Date(t.dueAt).getTime(),start=due-Number(t.reminderBefore)*60000;if(now<start)return;const last=t.lastNotifiedAt?new Date(t.lastNotifiedAt).getTime():0,repeat=Number(t.repeatMins)||0,should=!last||(repeat>0&&now-last>=repeat*60000);if(!should)return;sendNotification(t.title,`${relativeDue(t.dueAt)}${t.projectId?` • ${projectName(t.projectId)}`:''}${t.assignee?` • ${t.assignee}`:''}`);t.lastNotifiedAt=new Date().toISOString();changed=true;});if(changed)localStorage.setItem(STORAGE_KEY,JSON.stringify(data));renderCounts();renderAttention();}
setInterval(checkReminders,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){checkReminders();syncCloud('resume');}});window.addEventListener('online',()=>{setSyncStatus(getCloudSession().access_token?'Connected':'Not connected',getCloudSession().access_token?'ok':'offline');syncCloud('online');});window.addEventListener('offline',()=>setSyncStatus('Offline','offline'));setInterval(()=>syncCloud('interval'),60000);
$('exportBtn').onclick=()=>{const payload={app:'NextMove',version:2,exportedAt:new Date().toISOString(),data};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`nextmove-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);toast('Backup exported');};
$('importBtn').onclick=async()=>{const f=$('importFile').files[0];if(!f){toast('Choose a backup file first');return;}try{const obj=JSON.parse(await f.text()),incoming=obj.data||obj;if(!Array.isArray(incoming.projects)||!Array.isArray(incoming.tasks))throw new Error('Invalid backup');if(!confirm('Replace current projects and tasks with this backup?'))return;data={projects:incoming.projects,tasks:incoming.tasks};saveData();syncAllNativeReminders();toast('Backup restored');}catch{toast('That file is not a valid NextMove backup');}};

$('cloudSaveBtn').onclick=()=>{saveCloudFields();toast('Cloud connection saved');};
$('cloudSignInBtn').onclick=()=>cloudSignIn().catch(e=>{setSyncStatus('Sign-in error','error');setSyncMeta(e.message);toast(e.message);});
$('cloudSignUpBtn').onclick=()=>cloudSignUp().catch(e=>{setSyncStatus('Account error','error');setSyncMeta(e.message);toast(e.message);});
$('cloudSyncBtn').onclick=()=>syncCloud('manual');
$('cloudSignOutBtn').onclick=cloudSignOut;
loadCloudFields();

if(IS_NATIVE){$('notifyBtn').textContent='Enable reminders';setTimeout(syncAllNativeReminders,700);}else if('Notification'in window&&Notification.permission==='granted')$('notifyBtn').textContent='Reminders on';renderAll();checkReminders();setTimeout(()=>syncCloud('startup'),500);
